### ISSUE TITLE
Can't uninstall caddy.

### ISSUE THREAD

**Issue by baratthuj** [dab2020/JF-secure#1]
Plz help me to uninstall caddy service there is uninstall.exe present in caddy directory but it uninstall jf secure caddy still shows up in local services after uninstallation

**Comment by dab2020** [comment]
Well, hopefully this should work
Download nssm and in the folder where nssm resides, open a Cmd window and
type NSSM remove caddy

**Comment by dab2020** [comment]
closing this issue due to a lack of follow up
