### ISSUE TITLE
domain chooser.exe - system error

### ISSUE THREAD

**Issue by Voutika** [dab2020/JF-secure#2]
![image](https://user-images.githubusercontent.com/31569329/137649060-1b33d9d1-8a80-4a54-a513-0946a2ef7167.jpeg)

“the code execution cannot procced becuse VCRUNTIME140.dll was not found. Reinstaling program may fix this problem.”

When I press “a” show me this window, how to fix this..!?

**Comment by Xaiamasters** [comment]
You need to download and install Visual C, You can get all packages here https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by dab2020** [comment]
The answer left behind by @Xaiamasters is correct, Though I would recommend you to install them via the [official site:](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
Thus I am marking this issue as closed and will be updating the Readme to make sure more people don't have this issue.
Thanks for contributing!
