### ISSUE TITLE
Invalid DNS identifier

### ISSUE THREAD

**Issue by ghost** [dab2020/JF-secure#8]
Trying to run JF-secure v3.1 and caddy.exe keeps complaining that the DNS domain name I entered includes an invalid character. I've made sure that all my DNS settings and port settings on both my router and pc are correct, just cant wrap my head around this one.
![JF-Secure Capture edit](https://user-images.githubusercontent.com/105636041/168729471-c2a5c543-4b2b-4755-be84-0d7a04335441.PNG)

**Comment by ghost** [comment]
im having exactly the same problem T_T

**Comment by dab2020** [comment]
Hi, Thanks for making a Issue 👋

I have to ask a few questions so I can debug this issue.

Can you share your Config file (``` Caddyfile ``` from your install location).
There should also be a log file in the ``` ./log ``` folder in the install location, could you also upload that as well.
Is port ``` 80 ``` and ``` 443 ``` open and directed towards your Server?
Is an exemption in the firewall made?

**Comment by dab2020** [comment]
Out of curiosity, I decided to investigate and this is what I found.
Using the domain from your Screen Shot I pinged it to get your IP address


![Ping](https://user-images.githubusercontent.com/79893903/169448895-85caa8d0-2fdd-435b-83c6-079abac25de7.PNG)

And then I checked if the ports were open using a online tool and This is what I found:
Both Port 80 and 443 are closed.
![80](https://user-images.githubusercontent.com/79893903/169448993-8ca0ff9c-adb4-4462-b221-9a8f804ffbf5.PNG)

![443](https://user-images.githubusercontent.com/79893903/169448998-a598a808-3a21-4cb2-903a-5a3f5ff1b8d0.PNG)

## Opening the ports securely is an important step for Reverse Proxy, You cannot expect it to work without port 80 and 443 open and forwarded to your Server.

I'll keep this issue open just in case something else comes up when you post the logs or config.

Now if you are sure you opened the ports, you can check if your ISP is blocking the port, many are notorious for doing so.

**Comment by ghost** [comment]
Hi, forgot to reopen ports 80 and 443 so I did so as demonstrated here:
![Port Capture 80](https://user-images.githubusercontent.com/105636041/169685247-3be2048b-fd02-4fde-a6f4-5752d5e08c34.png)
![Port Capture 443](https://user-images.githubusercontent.com/105636041/169685251-ca33eb6a-9282-4341-83c6-3bca9aa489fc.png)

Here's the contents of the caddyfile config file:
```
lilredpanda9.duckdns.org {
	encode gzip
		}
    reverse_proxy localhost:8096 
}
```


I couldn't find the ./log file you were referencing, not sure if this one is in regards to windows or linux. Here's what my installation folder looks like (I'm using windows):

![Screenshot 2022-05-22 011657](https://user-images.githubusercontent.com/105636041/169685493-6d50aa45-3858-4db4-9404-ab4df885b73f.png)


Ports 80 and 443 should be open and are hopefully directing towards my server, I have made sure to add the exemption to both ports in my firewall as well

![Screenshot 2022-05-22 012826](https://user-images.githubusercontent.com/105636041/169685841-c936b21c-fe6f-4e5b-806c-f303e6b2dd2e.png)
![Screenshot 2022-05-22 012341](https://user-images.githubusercontent.com/105636041/169685649-006b64d8-e61d-4fde-8c99-ceb397893904.png)

**Comment by dab2020** [comment]
Try changing the config file to this:
```
jellyfin.duckdns.org {
	encode gzip
		log {
			output file C:\install-location-path\logs\Jellyfin.log {
				roll true				
				roll_size_mb 5			
				roll_gzip true			
				roll_local_time true	
				roll_keep 2				
				roll_keep_days 7		
			}
		}
    reverse_proxy localhost:8096 
}
```

And create a log folder and ``` jellyfin.log ``` file in that folder

**Comment by dab2020** [comment]
> Explanation for above changes

I can't accurately trace the problem without logs, so this will provide us log and hopefully I can fix the issue

**Comment by dab2020** [comment]
Surprise, Surprise!
It's working. Your domain is registering and showing up with Lets Encrypt SSL Certs.

![working](https://user-images.githubusercontent.com/79893903/169688287-1bdcae8a-f30c-49bb-a1a5-35f102c45dd4.PNG)

The only problem the page is blank.
This means that Ports are open, and that JF-Secure and Caddy are working just fine.
The problem likely is the JF server address, is that correct?
I can work on it more when you upload logs

**Comment by dab2020** [comment]
Okay did some further research, We have a few possibilities in front of us.
1. AT&T, who I guess is your ISP is blocking your Incoming traffic. This Reddit comment perfectly describes there position on blocking traffic is
> "Does AT&T block ports for incoming traffic?"
> Are you an AT&T home customer? Meaning you purchased a service intended for homes and consumers. The answer is probably yes, or yes, but unpredictably.

So such a preposition is not out of the question.
This is supported by the fact that your IP address or your domain do not respond to ping requests. You may have to Talk to AT&T. You may have to change your NAT type.

Try Navigating to your domain on a local network as well as accessing it from the server it is running on and see what happens. Make sure that the ``` localhost:8096 ``` in ``` reverse_proxy localhost:8096  ```  is replaced by whatever address or port the JF server is running on. Make sure JF is running.

2.  You have a over aggressive firewall, either put in place by your self or by your ISP.
3. Is there anything running on your computer that might be using port 80 or 443
4. Upload the logs, and we'll scan through them to make sure everything is in order.

**Comment by dab2020** [comment]
@cybergeek2000 just alerted me to a important factor in #9. Your ISP could be using CGNAT or Blocking ports.
And AT&T had a [History](https://forums.att.com/conversations/att-fiber-equipment/issues-with-hosting-and-port-forwarding-cgnat/5f480dadbd25505071358f02) of doing so.

Plus I am now 100% sure that Caddy is working as Analyzing HTTP headers to check what server is serving data, gives us this result
![Confirm](https://user-images.githubusercontent.com/79893903/169690202-40966c88-7534-45af-a64b-93d24d9e70b7.PNG)

**Comment by dab2020** [comment]
Don't worry about leaking Domain and IP as I'll edit all posts later to remove those

**Comment by ghost** [comment]
Figured out how to run caddy.exe from the command line, replacing the caddyfile with the debug stuff creates an argument error for me
![Screenshot 2022-05-22 041753](https://user-images.githubusercontent.com/105636041/169692576-e3a75ab8-fd5a-413d-b351-e0cfadf95982.png)
![Screenshot 2022-05-22 041822](https://user-images.githubusercontent.com/105636041/169692584-dabaeaf7-aad8-4010-8457-91a8b2eb5105.png)

Yes, the problem seems to lie with the server address. localhost:8096 does point to the JF server address but entering the actual domain name in a web browser, whether it be on the server client or on another client on the same network, fails to load anything.

I'm not sure if CGNAT is preventing me from connecting to the domain name because, unless it can cancel out the pinholes I set in my at&t router, it should be able to bridge http connections. 

There shouldn't be anything else running that uses ports 80 and 443, this is the first time I've ever opened a port on my computer lol and I couldn't find any other services that required in/outbound http(s) connections

**Comment by dab2020** [comment]
Ok so Here's the thing: Caddy is not running as the file path is incorrect here's the correct one to use
```
lilredpanda9.duckdns.org {
	encode gzip
		log {
			output file D:\"Program files (x86)"\JF-Secure\logs\Jellyfin.log {
				roll true				
				roll_size_mb 5			
				roll_gzip true			
				roll_local_time true	
				roll_keep 2				
				roll_keep_days 7		
			}
		}
    reverse_proxy localhost:8096 
}
```
Hopefully I added all the information correctly.
For File Paths with spaces you have to use "" marks
Make sure that the Folder ./logs and a Jellyfin.log file is created

**Comment by ghost** [comment]
Ok, I don't know how this happened, but after fixing the caddyfile by quoting the entire file path everything decided to work perfectly???
```
lilredpanda9.duckdns.org {
	encode gzip
		log {
			output file "D:\Program files (x86)\JF-Secure\logs\Jellyfin.log" {
				roll true				
				roll_size_mb 5			
				roll_gzip true			
				roll_local_time true	
				roll_keep 2				
				roll_keep_days 7		
			}
		}
    reverse_proxy localhost:8096 
}
```

Here's the output that I got in the windows terminal:
![Caddy Capture](https://user-images.githubusercontent.com/105636041/169714621-6131b002-c154-434c-945e-9adf445fa2c3.png)


Here's what jellyfin.log looked like after closing caddy.exe:
https://pastebin.com/hKRWSfU0

Everything seems to be working now I guess. Thankfully I didn't have to contact at&t lol
[lilredpanda9.duckdns.org](https://lilredpanda9.duckdns.org/web/index.html#!/login.html)

Also, the server only seems to run when I go into windows powershell, cd into the JF-Secure directory, and run `.\caddy.exe run` and not when I try to run the `JF Secure.exe` nor  the `caddy.exe` executables from the file manager

**Comment by dab2020** [comment]
> Ok, I don't know how this happened, but after fixing the caddyfile by quoting the entire file path everything decided to work perfectly???

Oh Wow! This is a surprise. Must have been a glitch within Caddy.

> Here's what jellyfin.log looked like after closing caddy.exe:

The logs appear normal there is nothing in there that indicates anything out of the ordinary. 

> Everything seems to be working now I guess. Thankfully I didn't have to contact at&t lol

In my years with AT&T I came to the conclusion that they have the shittiest Customer Service.

> Also, the server only seems to run when I go into windows powershell, cd into the JF-Secure directory, and run .\caddy.exe run and not when I try to run the JF Secure.exe nor the caddy.exe executables from the file manager

Thats coz they are console apps. Press Ctrl+Shift+Esc to open Task Manager, and click on more details and then navigate to the services tab. From there Scroll down and find JF-Secure, if its running you don't have to start it manually.
