### ISSUE TITLE
Add a additional Feild to ReadMe

### ISSUE THREAD

**Issue by cybergeek2000** [dab2020/JF-secure#9]
You should add like a warning that people should first check thier ISP rules or their practices to check if they support doing this
A reditor made note
>Please before you start, google your ISP name and CGNAT, as well as ISP Name + Port Blocking.
>My ISP was using both CG-NAT and blocking ports on ISP level. A quick email to them to take you off BOTH is required for this to work.
>This drove me insane as this was the issue my caddy wasn't working, and returning errors.

**Comment by cybergeek2000** [comment]
@dab2020 Sorry for bad spelling and grammer

**Comment by dab2020** [comment]
Oh Wow Hi, This could not have come at a better time, I was dealing with such a issue just right now in #8
I'll add that to the Documentation
